version: "3"

services:
  # PHP-Apache
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html

  # MySQL
  db:
    container_name: db
    image: mysql:8.1
    ports:
      - "8081:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysqld-mydb.cnf
      - db-data:/var/lib/mysql
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db-data:
